# Generated by Django 6.0.3 on 2026-03-31 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('duracion_anos', models.PositiveSmallIntegerField(choices=[(4, '4 años'), (5, '5 años')], default=5, verbose_name='Duración')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=30, verbose_name='Código')),
                ('ano', models.PositiveSmallIntegerField(choices=[(1, '1° Año'), (2, '2° Año'), (3, '3° Año'), (4, '4° Año'), (5, '5° Año')], verbose_name='Año')),
                ('cuatrimestre', models.PositiveSmallIntegerField(choices=[(1, '1° Cuatrimestre'), (2, '2° Cuatrimestre')], verbose_name='Cuatrimestre')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='horarios.carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['ano', 'cuatrimestre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado')], max_length=10, verbose_name='Día')),
                ('hora_inicio', models.TimeField(verbose_name='Hora inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora fin')),
                ('docente', models.CharField(max_length=200, verbose_name='Docente')),
                ('aula', models.CharField(max_length=100, verbose_name='Aula')),
                ('primer_dia_actividades', models.DateField(verbose_name='Primer día de actividades')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='horarios.materia', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MateriaAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='horarios.materia', verbose_name='Materia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Asignación de materia',
                'verbose_name_plural': 'Asignaciones de materias',
                'unique_together': {('usuario', 'materia')},
            },
        ),
    ]
