# Generated by Django 6.0.3 on 2026-04-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='duracion_anos',
            field=models.PositiveSmallIntegerField(choices=[(3, '3 años'), (4, '4 años'), (5, '5 años')], default=5, verbose_name='Duración'),
        ),
    ]
