# Generated by Django 6.0.3 on 2026-04-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0003_duracion_3_anios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='cuatrimestre',
            field=models.PositiveSmallIntegerField(choices=[(1, '1° Cuatrimestre'), (2, '2° Cuatrimestre'), (3, 'Anual')], verbose_name='Cuatrimestre'),
        ),
    ]
