# Generated by Django 6.0.3 on 2026-04-01 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0004_cuatrimestre_anual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
        migrations.RemoveField(
            model_name='horario',
            name='dia_semana',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='hora_inicio',
        ),
        migrations.AlterField(
            model_name='horario',
            name='materia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='horario', to='horarios.materia', verbose_name='Materia'),
        ),
        migrations.CreateModel(
            name='HorarioBloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado')], max_length=10, verbose_name='Día')),
                ('hora_inicio', models.TimeField(verbose_name='Hora inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora fin')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='horarios.horario', verbose_name='Horario')),
            ],
            options={
                'verbose_name': 'Bloque horario',
                'verbose_name_plural': 'Bloques horarios',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
    ]
