# Generated by Django 6.0.3 on 2026-04-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0005_rediseno_horario_bloques'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='aula',
        ),
        migrations.AddField(
            model_name='horariobloque',
            name='aula',
            field=models.CharField(blank=True, max_length=100, verbose_name='Aula'),
        ),
    ]
