# Generated by Django 6.0.3 on 2026-04-02 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0007_manager_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(choices=[('bloque_i', 'Bloque I'), ('bloque_ii', 'Bloque II'), ('bloque_iii', 'Bloque III'), ('bloque_iv', 'Bloque IV'), ('rectorado', 'Rectorado'), ('barco', 'Barco'), ('chacabuco', 'Chacabuco y Pedernera'), ('normal', 'Escuela Normal Mixta')], max_length=20, verbose_name='Ubicación')),
                ('planta', models.CharField(blank=True, choices=[('pb', 'Planta baja'), ('p1', '1° Piso'), ('p2', '2° Piso'), ('p3', '3° Piso')], max_length=5, verbose_name='Planta')),
                ('nombre', models.CharField(max_length=100, verbose_name='Número / Nombre')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['ubicacion', 'planta', 'nombre'],
                'unique_together': {('ubicacion', 'planta', 'nombre')},
            },
        ),
        migrations.RemoveField(
            model_name='horariobloque',
            name='aula',
        ),
        migrations.AddField(
            model_name='horariobloque',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloques', to='horarios.aula', verbose_name='Aula'),
        ),
    ]
